debug: false
management.endpoints.web.exposure.include: "*"
logging:
  level:
    com.example.fastCampusProjectBoardingApp: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace #jpa??? ??? ? query??? ??? ??? ??? ? ??? ?? ???? ??? ?????? ? ??? (????)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: gon
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: true
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated

  spring:
    config:
    activate:
    on-profile: testdb
#    datasource:
#      url: jdbc:h2:mem:board;mode=mysql
#      driverClassName: org.h2.Driver
#   sql.init.mode:
#    test.database.replace: none
